version: '3'

services:
  frontend:
    build:
      context: ./frontend  
    ports:
      - "4200:4200"

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yoel
      - POSTGRES_DB=angular-golang-users
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres  
    environment:
      - ENV=production
      - DATABASE_URL=postgres://postgres:yoel@172.17.0.1:5432/angular-golang-users




volumes:
  postgres-data: